[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "bb8ecd4a577d696623d53eeb7281f0b5735492b1"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "a16727781aed87bcfe2dd9daee86b38fd374ebebe54a6968e2b1a08028c06aeb"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "2d747ac56a3f8d81d7a1a3a990914bcb5107361c"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "7a1665c926793da2e39bbc411b870c990631d1796ecafe3fbf82d1bff30ab7a6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "3ad62503112f102443d03fdea701ec3dc80c0411"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "5a9b1880bfd6a0dc000fdcdc2be4481c20f9461269998d7af674cf0455100e92"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a31ed96ea1b5200efefed1b785fa52dc9ba65421"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "5629a83733149dcbfe6c885447c4462d401e42ee06bee4e286d4a29e6f68c37d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da010159394552561c4e0ef32fdda206f28ede91"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "c2c2d88f72ea0cb88c71c36ca808970c3c2d9dbae95dedcccee0683d5b42478d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "powerpc64le"
git-tree-sha1 = "204278398aa0669a9d4df6da972cfc096eb25500"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "b791494aae4dbc39e5584f91e2fea7633542b0ea12f810f6b37f343b29bec41b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "87cbc08b5213538f3bad4ef1ed46f72f98ca7bc3"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "f724a49454ddc0f8aec58757236066300a9573ac17f261cb3d26f367a87382b8"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "eda785b3c279e38775cf6a071939c98a60ac3b44"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "1083ecbcb41b98c6ac94d3ead72f061b2dd5df3bf3a8ffda2b62f7131a11619b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "f63c30ba8a77f4a258001c7a664543917420a0de"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "dd44a08d0baed923ca1a265dc33a2be08fa921d22f8762df43f3903783032939"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb30069cb0f3dfd16c95dbe808c0de13781fd4c3"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "a8d194a7c170bf49a53060c405845f91c9c006ffb76e765b6badb08336c66b0d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2cce06470827eb50327ae5e7366998bde62bca51"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "a8ce551ced8501167d50a14b0389e98033362822800ec7563c7b1a2345f8738d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "050e47301c6fc31836bd4b9f53a44af29ee1715b"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "fe1a2684048fe5591d7e98b7a87bc9d89837321a689ccc0bb3bdab5f95169734"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "f508928c5af6a321e7275b52f8a43544fc5c8f81"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "d454dce654a1e4cedf4242e0f32da960092b7eb71f219d208a9ac6d3e528b5a5"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "701669f35ad5f84c10ac51c9c3684c366dc07da7"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "0ef310408121e6fd6b55c07bbbab939d7ddd6b3832d79c8b4d218466ba2f893a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "cacf17f207f7467d6811dfc196b21d63cf12e607"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "6fadece445f81924119d3bbbf3106edaf2a49039c4474f8653b478d1b0776574"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "9537d197d6b5d61a7ddf06049280e7538f838227"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "fe85455ae41fb68fc3c4d3209f31d4786b14ea3830b094e0a1e629e4d34ad2d4"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "467cf6256d5cb40c40fef2c5c23ea70256d2db92"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "0a85a98e1eaf6295bf69417006e7392531a3951ee4f04a5e586ace29922d1214"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "9795602333a245a25986cfb31dc722d22604b412"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "f08ec1406a29db967ea66f19f5f7b5521e620b71d7f3f6b207345140650f7005"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dfc132510810201954fa64898cd5c9bd61fe353"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "e785de11700da7c790a05a9278da445cc6da4801a24af357be7db8de6702a6ae"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab83ef460184148e5394bbd3f15997c5f5b0cc44"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "13175bfedbf7ee7a5ffd68c8b1b7054f08221b11089372cea8da46c5f05daab0"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "77f455ec8e59988c3349b64b2d0fb538834114dd"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "bee78e2b58c2be7e7b60c22712b99c97cbcee19aba0f2848512b4aed921cf55a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "11bd5131e8ff515f7dd7e5b4538fdefa92a7e536"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "bf451dcc6ab4a9ecfa3e4671fb6ebae3474d55898520d7f8b272ced63dca16aa"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "00fbe4db2283d379627bb33903a116fba1195b87"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "e552572833a7b0e3e84504f3d2b7885b4545f40f55623a933688ffa7efb75d73"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "0551a733b51b86741e6b97b300c884db4cca943d"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "151e177ac18aba4f314ec29d9f5767e0f342ebe344c76371f06e855819a935e7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "798c97e5f6961728cfb2bfbef15c39ca935aaff7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "8a3f0869562c68c7af655c80acb0309a3445d5279d3301c72c3cffc78d3edf54"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb392a3b71b879c5289083097b930f7e1df87caa"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "9c1de20470bffdb9483e117c67ef6eb432e18d3c8554b597bf5260505682a02c"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "db1ff8fab727f683d5f8ae790add68af3fe69c6f"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "9fee6b02b880b97f0c635f4931a145c027a87b218163cbef50feb91b3f1ebc69"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "e9b38a7019c7254abe63831616d4fc60c059da4f"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "6d37999ae1a457e086bbda7b7d6604453c50675da1cc815bc0fa65f73a5da3d6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "fa428d4a2d1811e06d1bd003819fc3fa88ee516b"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "c7aed1a17ce35717bfcaaddb6e31d0a4b56be969a5ed325cfc8dc11303333f92"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "f694ee072249013aa3b9b413504b80f031e06d10"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "def6b0334c0a303362e74f827288e77135835d9e652ea0831ce1d74e3e0e7267"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "82149a173059bcbe617833966e055bbe79d8b040"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "e36581d2c06025ee7a210276e1fecddcc7c3ca63ea1e06928dc481ebb4b8a988"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "1f5e4c3ce7117422ac00e4244020ca3eb30f3fe0"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "ac99651a4a65140559f5939fc2b2ddec477719300298c04a4c09e3edf2e2a79d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b4c3a72145ce9f699e781fbf1184c0daf9074d8d"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "85371f5e508bbfceed4d19ddfa14213f36932423a0c146fa6f3136e0f1cfaac2"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6007f62095040c8cce100764a76dcb8d44dc9a7"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "fcef5925fc17e803f9c76880852bf22954a921157ab60325d0c201df2334109a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "487ab73b6b3c6868beeac3fc2665556003ae8895"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "8e9dde6f1ee4bb2bedffb5e5321d06fef83f127a8cc6b16243190722860395f1"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "2a64edf05f80b719aaee64f5665075f77e2a675f"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "c48c130cd2988a95697565d8e4c3547a3346fcff7d790d09e7d6af6c74712555"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "de03d3b1defe4183742eae0844add692d130d94f"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "ab1b09cc9fade79a15ba6fbf5dc25f1eab299f37b044dea0b1740c4f21908ab8"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "f3ee5deb4c9a3fc93865a37888d1690d5cd143a2"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "d38566494a98c825cc32becbec280f58b78fb72906550f5af62ab1ba8aa6b61b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e47d118479b97065c61b9caff5706cb52ac4f230"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "e53d833f7d2a599ce855a1bdac3c0ac2c041700ddd6c71fc4401239dd3857ca4"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33b4da7eed9615245e301cbbeee3250a87f72fd2"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "4d46084ce2bb867f893bbc05ecfb9760a4d594e00948ba86bdb061f3c949a895"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92a7139cab9b9d2ebe858d038f9d6a8c29f3550d"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "bde5a7c4cf9a8253c87fe2e56e6dc0ab7bcbb5db883ad327966bfb3abb881704"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d734bd6e1b4cf7e533fd51d160040c8ae0f09a5c"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "21a219ea1c7f66b77f64046cc880b672c893a6bce28adc8351326eea4d34d18e"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "a9f865f91e92df08a133efbf47032572baf8a8e5"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "67442f6524f7798ce477252379ba09af8175bcaa875c8ab11d41537294fc23ef"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "182e2b014916c08ba5cf9fe05b23aa0ac00a4f71"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "f2db5d3403570112f9d2dc0cd3b6a8ff07b999334fbbabb079d8f09269369a6b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f0c298e0b56524dfbc58b8963f73b0e1ad4100c7"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9391bf71f45cd2e8ef20c22584490970cff064837013bd8c2282d42002514b34"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCC_crt_objects-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
