[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "6dbbbe6db206425766eab3d46493b73c7e5edd3a"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "6ddd9d20f3a330101662b40675d5399907d4a7012ead71c8fed3c85367b5e3cc"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "675200a94ce1a0b7559ba616daaf45b7156cd801"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "e0233f5d67bc51ccc74af47f094480364648801a4e5c27bc966f6345944d6bf7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5a2a5a523e82e2043021063135597ccb152d9ea1"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "39058fb95dfe76ed65d6a1610d4ec79c218cb32b2aa8137e4cd3f8e8bc72c168"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
