[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "0c42173853126966a9306a1b3cbc356ed4bc66d2"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "6f0e733dfa07a46739749eb2aec413f849b5adbc471081a01e396f7586e16428"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "1c81bcc81c343f22609d884aa7e941806c15cf36"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "1c789e6b68d15bc8d4af28b00c493c3ddd0740f3ba21db9afcba3e465690f7ef"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "9eb591cb0e5b7c31edd6acef873f54d3f9d50df6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "0990aff989758db21829bddc42bd2e904b4a25d1ebfc0396922e257071352fc4"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-build_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "381d839a27b773b4de28751bf0f5f48a3564c7ae"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "b2fb8aff6d613302ad8e9b6dc6fde217c1c86dcc516051ccae7c6d491148db92"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-build_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "00b0b0436e7116edcb2d6d22d8dd3c143037a14d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "0ec72ad8393e2eefeaec92631367dbb09386b2419bd7b06938f23ba25f88d3dd"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-extract_log-v9.1.1-aarch64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "98a37a72ce0f0a58ee22b67bee578eb54ca51860"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "7a065d6dbdb302041860afc4e4288048d8ca0ce196d8f50731cb1fc42a874507"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.1-GCC/GCC_crt_objects-extract_log-v9.1.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
