[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "96518e325d517c9a605b3a718d100c9b589d3d6a"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "ba79760a5ae2674455e713dcfd0ab681f0ab4969cf55ef9f62c396eeaf73f49d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-aarch64-apple-darwin.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "01ac9c7f62ad87dc885c5d5b99901e0c5e110e6b"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "9814163ca81f4bc7142e5c5240b236b87d7711f2e89db91ce07f162458dc0464"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "08184663c064d7c03ed2a894bb52692e81a0bb52"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "a2744f18ca2b956bc42c76e2c3076b620bb699ada7775455699d182429d086f7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "7533848b2086adc3cbdcd5de9bf4a76da55f7337"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "0069a793c6644e3dd65f89605db2270c2486457d4cf88d73568c1d769eece8dd"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "632646230356bde4cbebba55d56be130b5c10c24"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "af019548fc23e6ee8f872bb535b448c1f036b6d05673ad0c6e44c495394fbd0b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "14519c95f1e395f70b28c76787dde707adb7b01e"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "96f4f96ba11c70fcd11e3f175d52b780ba10aff94e2742e9bf896b7d292de862"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
