[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "8c7b071ee89c915b9666cfd1e813e03a082f4812"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "94c0287203b043e5fb6b42a1b4512d4b76ddf37d423b1da889ebd29abd69ee8f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "64b42d9ebd7c3afb1d35f70ae46e93c3cf12c4fa"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "ca81798ad35b1a4f066e08a88171719110bad90e0528ca04fd66020be65f93e1"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "7e9699ae031931fe00a00ed649dedc107b315040"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "b7fa73fc1d116837dbeef1e9aa98f92b381d355b93de04c0bf73a9876a108b18"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "faf92b8d1c67e9a1a084e54a35944191a90c0aad"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "73415566f3bfd27a615c70d850d783c68b4658f19b88482dafeb715355f162ee"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1dc29f7e6e3f4b7eef89d668a1f63a63095377f"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "cb1b736a3154bc6ea8e05278de129f832967c8125d15c66d1ef12b5054bd5863"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "powerpc64le"
git-tree-sha1 = "fe4e754653a4e80fa5fbf4997e06842762a01cc2"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "be1833b6a3427784d8973948cf09cd8075d182eba99764bffc090c922838158b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "9fbc197a6c7918834f49934b703bf2043a53b761"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "a7df94293a0bdb6fe5c0d7f76ca53f65167a72e09f72a4d485e2fb7422429539"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "5269691613599b475bb985c8746ee8e9496a30a1"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "3ce2b7ed0469b5200ef6cd7b855bddabd9280ad97bd52c43935d6676011eac30"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "91da11b6c78c07e7e71b588e7b45f3143b140aab"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "d7a12433a094ef72c4b58ccea81d80806b55e426e042f3f6d1efb55f541528d2"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf9d27fd2a5caf0ccd4dd65e3c049fc7f58af2f9"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "11eb918ebe6484038346d8a72c218b0b40bb87f80059ab8e4556f7ff05445b51"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81dfb50a181869672eed218cc70775168dafa0ea"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "5455e5fdf4762a9b771aa46c665fa882894fd4cfa8ac3d8fe0fa93f52ca0bab6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "0efea7a6bbc12962247332a71911b407c1136a6d"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "bf2434bb2d51f96f34c44446848bd39d1f2526e6da37136155ff553f9a5bb2a9"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "c5a9b6c55b742867b81207711a5dccd693dec165"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "d41c5480f9a5c4c351b75615b37e2a0d5fe498ff783b4fc9718dabe4132d9452"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-v9.4.0-i686-w64-mingw32.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "b263a61b215b16fde4e1f21be7c1b97721b45157"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "34de7d2757b4d2e28a45f5fbcd54bd5a92dd906e841d8460c347ead7cb158c9a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "504965f25c0ed474965947f1dcb1559eeeb23d55"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "474f105f494e982be23e1c56a4bcd1f02acf04e05c7fb052e83ddffc1f6f62c1"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "12cf00ad5a36ac11b6bd46120373a8285baa6ec4"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "0c352546f21f5608d7a9d86d507b461d765117400135da7d8c1529d850a51657"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "48b6bd960424934dabeaf1f4047e74c3f26815b0"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "c30b8447d917a7e47e7b9fed8f6f03088ef962679fb7a3557a5dcbef49fdde63"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0b9371405b75d4741fcc6ed6fe53ffa8f358555"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "e2659d1430f933db307be30b2c9631285df3aabf16a439be37b70be148023872"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "81e7b20703288c8b5205997a9f57e6d6baed5972"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "78f4821cbe1b76ea4a25f327ea75dbc3a5daa109686ad505e45a5d25c0b1a8cc"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "f9cbf1f453cb18a89a1d16028b61105dcc3ef9d6"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "a97692ada32b78f476b1069c59dfd9da17b4960b8fac61ff5f62eeba007a9c3b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "2273e91177944b9a92fcf003a86b455a485c5cab"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "a042359ef1f8211a9291588981557d409565071cb217faca32bb68aba7f8890f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "c83b6eb606aab5d7cd320443f5c781c08cfcb968"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "5f7d204f7adc6d6213f6ac2d44c46c3fb947892856e393c99687194d6a7eb7df"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "abda826818d67e642fc991a159e579c74eff81e7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "78272eb2b3ba24cd62da9c6f2af30843afcdac8aa15fe8d3d48794e31c3814a2"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "184ff1d963481f9e097ff81bff5268779525309e"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "1ba8d0b5fa43b98f7b45ac5ac51117dda6402b090b16ba73624634a4b68a738b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "56d5cf49b4f03447a6b4e10e02fedf823511b554"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "5ebee3bec5d8ea86868cfd1de2de1f0350611755d08558d522a340f211d4a0a0"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "910074ac649906c1cdac1fe8e80de171604364f4"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "5232aa89a1593b14b41aa3556a4190ab11440cd08cdf7754a129d8c9b0a0aa12"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-build_log-v9.4.0-i686-w64-mingw32.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4bdcfc3cfc045d25eee6823961f64dff8d28e1b2"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "a3f56843a39aca62c8e2cff7a77058233d6dc3e597551694cecea40ce0026f72"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "e43fb611bafa977c8a162c896e503041f100a7bc"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "b16efb04fd2a3dd8ff8e62ae30c5fd16e1a59aa37182c0a271f6afa733a0b672"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "39d2ad74872d0aa74b7d1804547ee2710cbab039"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "58e9c7616404bab4d4bf2e4714e3a2849cfdb49295b2e3fe0f66de12b5f59333"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e49a84946f1496267c8a3e0a734c6dad805635e1"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9035cc2793a5432bfbfe18ff39b520fc11f49b1cf9175c75533511e000ad4e9b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebab20aad5d249a87e4d267ef1f63976d325749b"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "1c0a442694193f4ec01acd141d2c5a788fcd9b18b776fa673676faec9b17ae71"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "8e82d2fdb598a4c73dbd3fd60596d37834244e5f"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "e74152aafd1aaf9cc6973a8d8e3f82709a59e7147ea6cf017e075d856a2581bf"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "227826f4ec8e0ccec98b4df1911a12786559ed47"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "eed2090a3d1628564a71ae79598573ef532e03cf26dddff6510493a8b2c49eaf"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "78dd72e9c407d2b7c3fd83505a6ee5cfd18108b9"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "0adde1aca5437fee4b1aec0fbdd694bf36a52919cfbe7a03139ac2566dcb9d99"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a3a6caa71d39fd32c3f4cd76251f2957cdcef247"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "d6e5bf9b84170b188328192b67d82ebe273f227f358531fdf754c5a459500bce"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ca6c4e222cfb6d7146b69bfa45046fa78d13a6a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "d3f40258ed8b3dfae23d63509ab98ec5dd34239c4f3d81135f9812ab56b3b1bd"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52af4de2d9c8aedb5dd3de029469bdc8733c10f1"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9e8cc668e17bd0d640bc6fda474a1d55eed75c6231ba1339e80e0acc053926a0"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "49e50285ab18ed73aabc969bc9eeca21ef1d924e"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9db37e30d7102841ebe1c45530c515791be3ccac39e3a624fa23358eff816537"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "cb52fa0627d84bc0b396c919b45340740c20f5a9"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "010b9ca2b6bc60aa9c40542b8a97405d0dbd7b5617e9854c833c4a31488c5ba6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.4.0-GCC/GCC_crt_objects-extract_log-v9.4.0-i686-w64-mingw32.tar.gz"
