[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "5a133eec71a673cbc09622e5a1139394386ccec3"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "be45e60057331fe2764a5e98764546bc0db9bd48bc7035bc01d41bc44cfec5bf"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "7eb559152b4fab158b7a2c2ad3d74c63f453c60c"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "89ad4f577dea1d2f98da2286abb6e3de0b40c52019c9118299d993971a0854d0"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "b4e9bb9529f2baca1b1f0da23ddd3843029f5d98"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "50a3e57543e700e2b181c1f595b23a3d9b378495cc3480bdc4b4c8643797b390"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66d2859f212f42a6f11f1351c1bba009be0231dc"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "2cc3a95e76829171746dcf931e74edb36191d3729074c8dff01d36071b024009"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e551f9abaaaf3d483b8be7c900bee0bb5de5f921"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "7bc330bbe9516b6a109c85cc17dd4a3abe4b9e833912a6caf56f6f47f1aba434"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "powerpc64le"
git-tree-sha1 = "98c56d37fd117cf7fae79e7a6e8d3a0c6695cf7b"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "374c58dd9d67d3451ad7b6ed65dc2f7548cf3029d4704061ec70a35841daa3ab"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "0a231aba82db019c469215390a1f5550b579003b"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "7fbb115964beaa7e4f135213db5b0e7e097c73604d4c832e10315acf6fc1dbba"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "37a46af2a688140cc0befd74bc8a737caebbe6a8"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "995e31568d31de47e6bcd8a3a58c4d95fe72cc2fd2e47781e1c38995bc02091c"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "3a55cb7feae3c5930e01594e2749bf24f7efb114"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "601f7ce1427e7ba455804fc7b1b54eb6902f81cd6d46a1fcc5b39619630b597a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8344bafb9a9b3d8070aef273250ca23f7299e9c9"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "c77f80688db5a2d6f2ce39e9ad334a1641590818b3916b6af0ca98ade46d6061"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07fc3e044f6dd2ef254e4bc60bf966adb3246587"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "2d1ad0fa82728f6c185c30f0379f157243604a3957016942608882fedcb734bb"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "ef209620c68df0bfe50d1cf50f4bb5d140d5fbfb"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "cc3d232703998495c8b3f9d1c4509374c78a6b86386246f27619df6dedf15499"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "98033b46b4ac5f54abd3b1926db5963451655399"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "69379bd59fb524e6b46862a14c8fa593e95ae75446801e664db75b6c66f3ce6a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "6dbbbe6db206425766eab3d46493b73c7e5edd3a"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "5cc978130f3d7139f51e0b2a35e431d5935cd8362078f48dd37b4d095ba12c31"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "58bc47efedbb85cac1797e9c8b5ee5f1866a2409"
os = "macos"

    [[GCC_crt_objects.download]]
    sha256 = "db6d9fecd38ac48c1cf2129e479d3e7f212685e28e70eafd140df1463d9b3295"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "123b1469f104d47d9835925c9212ed382a682fdc"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "393a2c699ff85e982f804ee3ed7f0ee73fe42dae8712df277e6b97ca1a813360"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "1967cdf47d9dac8237735fdbf6978669afa3c74d"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "187371d8898efaa24eaca353a3d3c857eb9a327f5f946e75e16c1970d7df50ad"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "6f349c942500f1323f62d58a129de8b3557a4f93"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "dc19c5c308ff05b95e5c74749724a73de57628ddef6f1faace8576cd3cff2240"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e06e2c2b7b72e67dd5ae7f31663561e1823ec64"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "de7304b8e45db7859fbb7300b41f395d9fa5c7e366ae2ab01ca3040a02bf3920"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18d49b663474679964ea4161c5ee6250353f4327"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "fadb2f5060b9c2705529bc4a313f80a38eb4b240d49dec011d5a19d4eca00a3d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "82dc462e262db402193e461fd252c4aa285175fe"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "8b77176208dfce104f6756d4bd6874efdb7bdb7f0d227cf174a715a4947f6dd0"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "ab907ee1cc8a1f3fb4ebdf36727802abee081d37"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "1b10ce66101ebbf37f3da1bd9e63c556e2834a4f4592c5c28b6e56b2518b3363"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "5a893a577c6400c83b0eb5fb304a53aecc0bb2d3"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "6bcd9d33657700bc317640a9063ec87c3e4f16383d49515890fd092c56912040"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "65d77e77404b160d1ac8f02f7b08c820d2e10896"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "15ffae38f56e1d27cc87299d2aa804cf6096d0e1782d0175cca73750b0b56247"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b4f0c8a2d98d45e27b9b2e6cb4c7f7fea60bf04"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "11ca58aca0a6ba600ad6543eb097952018dc9d50069f4a7ffd158e74780dc03f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "684c3ff5d3794230baea4debf77f53a3d9815bd7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "72c9e6587544837b42f14f97abee12a8af711d24edd0e30cbb239a59972b782d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "b77e641837ba8d30b102a04db95ff64975fc17b7"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "4a4c078fc22221c75d67207fcd1dee9f024b4acc9d62872c8e0704fd4fbe526b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "313c2370f73b9af7abf8b9162aade7725dd9919e"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "847e8af741bd9a5f04bf6cedde5eb74edbfd5eaecac67e9fe863e8857f631186"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "6915231346968d4501e98fb958f56ec0a3551ab6"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "eb13608254549c5be1fa95f5da6e42f88769bd2336a45d276869455b511eaaa8"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "6149df285c0836cb668d75a22c8340721dfdc05b"
lazy = true
os = "macos"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "c8487f5a4e134a581dc0e52b33845cfcea821062a0379211a21efbfddbf8dfde"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ed87bb4a608b2b84b66eee95942d00946e144a2d"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "44ec2df1344c4e464a81e64f357b00bdcbb5faadaca63e55b9c2ac440aa87072"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "b1c5b7fa94c2323a64dca06d339cedb19afbf233"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "826f693902171e549a8d9c961cbcecda0bae5a4a090d7300f68e81f864006fd7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "0693a2cde6d07e8a986e464d9a12a285c20f465f"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "6cd6a3e0b92f5c33158d5ffa71a17db5c827d6b00f2e6689891b1d78afa0899a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bf7e1983ae389fc747a28840919b914208f8857"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "2b9a2eafdb603a1f3207b2b30104e098ab36a8efb62f27ad8506822df6e4786c"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c966dd8df634cab24b8620115ea054b697cd56e"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "6a07589c0c4e17f2a72ee99ffe109d61d3edf5fff68cae9991952d41ac493c78"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "384c53f495602b5b82fc869df3930619134f4384"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "371651a4e7c1702d28c599862d4f97c9e4d4a1ed493a05257c4dda04ee2fe29d"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fdff6e843aed5444644827318473e80219202ddd"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9c8a157e860d2d54b4c9b252f6d7653ce2a67d18ebd6a772798ee6e622ef6de5"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "9bdb6cd180108f2ea8c3a535b292ed8fb4a206b3"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "475ffc52e695717fdf8b1a8fc8e916033b19948618cd46ac8dc624082b0b7e1b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "15fcee4421b37629aef17c3158f4a53644acac2c"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "081093100cde6086713ecb5e11f8fc62fe078d6f37cf1dab7b28682623c6fc94"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff6c9542e96d2869f450850b36171606cfaea5c9"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "c908930e04b84f463f65a8f96ea8ffad58da3a2e409bc03fbfa3d6fe0476ce50"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "010f8a2a4752b10f320cce3895596a9ca81816b5"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "75d2ded5c1d6bfa043f75e638c8ade94b7ee19eb03b008f5c715a467ed736d2e"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e0ec3b0bb8272ab75263aaef264d1aab2ce6f0ca"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "f2214307202b44ff6637d135541659b2656311b74db65b2f1d585bb50780e2b7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "39a9ca6aa49bbc78a32d6187ff70f0af01691bf9"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "d79d69f4089f8b70754fe4da59ee96f99eb522244df30ffc2ed782c4e85f548b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "883e9a76201d855336fd4e9f772698afe8aab02d"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "3e37c74eb7e7b74ce08871da64eae4d4c66f87d57d450036b7a2b941d3febab9"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "38978e4d1aef96e52df4e92081ffe66946cc8b6c"
lazy = true
os = "macos"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "73c9f06a472cd714d044e6d7b6674886f49ef8b880f8c6e5353b5f5d74a80cd7"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v14.2.0/GCC_crt_objects-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
