[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "0c42173853126966a9306a1b3cbc356ed4bc66d2"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "cf86f4671db82e1af0aaa4949f99f608235c4bb1983c10dc198b6c2af5381006"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "1e392dab256e5e09aaf9102aa9baa92f02c67525"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "63657e27df38e11339f0ac079de1b0c15159ca03a9d7afeb303317b0dffbbac8"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "cfd6c0fce873d3cb24441b7d1df4b6323fe5467f"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "b9274ad83d96c1aff86f69c5c57a2a75e3529950a4fca7024d0f2822b2f6a6fa"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd1707ef437f8a0deb802c300ba40fed9402ea8b"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "3eeae7c101e6dbd3e563205ec7e5bf95cfb35b9738335846fef69ffd8e427014"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4c3888bb3f356ea222106a83987c19338623be62"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "aa298eb218119133b6323886dd00799ce01a01be67798a94f61a357f09ef95dd"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects]]
arch = "powerpc64le"
git-tree-sha1 = "e93e93a69449251eae0732b50a1e0bb01673a1c7"
libc = "glibc"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "58025e5133b1949e5ce13011642a7b022ff614cb2be46d6a16c142e062492c06"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "a9af3514e59f89b4451a87ad464e7b9046906e6d"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "1bf8bb74e5df6b55c2f9f5eb3905311a2f546aa8e678cd54e64c602c8c60ee02"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "8ce15e95cfcda4b27b3b5850a6b75a9ab66a815e"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "834d02795f6b549cb0c2d031593d2f1559716a426b69330b292cc177754791f9"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "aarch64"
git-tree-sha1 = "2a494d09fd49a8f5f9019770e58acb0b6891eaf4"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "f3ba16616921eb240d48015ffa82adcea037425c967fc446ee82d0a271a48d71"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "076986582b04bb900f97ee1f959bbdb90fed3f89"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "0e7fc7e1cd08cc989c0f8ccbf1a0d36973b3bfaab60ea240601e89a373796d51"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ce1f1f1e515e7573279dd11d6a616a0ff6d51b6"
libc = "musl"
os = "linux"

    [[GCC_crt_objects.download]]
    sha256 = "db56b69cc2ca0e88efbe4ecceb54497a6004948c21da87305e845f48bf5bffe6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects]]
arch = "x86_64"
git-tree-sha1 = "0ac54c338779be666d1ff8442de5dc533edcaa13"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "3c0f986cb304fe3dba397c10f320209680da55061b21b4362288a351474f024a"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects]]
arch = "i686"
git-tree-sha1 = "d4683fc66787b06ae5f6e789c8732d95d2184f4d"
os = "windows"

    [[GCC_crt_objects.download]]
    sha256 = "f6f6930c4ea2c9cc9c27846ce28dd9b16a2cb9dccf87f332a8ca2df915555622"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-v9.1.0-i686-w64-mingw32.tar.gz"

[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "452fcd4873742a111eca232eb513cc0454cc2771"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "d9c62ee73a61d432249a235c473f8b791898985fbb104f3d6c0cda5e33b1032b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "4a250fe30b4e46797ed1cb56ac41b8120ddaa8a4"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "0c7b732c8d039e855e326fa17ad748bd5a233ff07b6bdfac9b0fe3c99b4bf74e"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "4d0668254cbe04bc3a7ff585580cad611a8d5a7b"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "b1beac29f690df046c012405965a2aa78947c87e34b548a6f025eb0b3db8f23f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6539ec0deae8052f09e03c9f3490f40c9b004760"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "509ad318f8bf73b0c636c32e8048fe3741007bab282da80a891436c58f6f258b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48ab02beaf265a5a0746d388ce0ed8c3838b3b61"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "1d57dbedf63b0bed041ea6a62f548d72419bba956768d66ed92d40ef916f0138"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "50cafaf60a5ef88da94ee581aada993f606bf436"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "bc046599ba6da3392835d48b7f1a107acfb1526f33a3254ee0b640cce4f45ba2"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "7fc91a4bfc1cf90bd7f457cff5ab7c84ce168b0a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "4cefe2cd0ce82de7363b4bd234116525d5c9f761eecd4788c2557d5c3e73891b"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "a3f8ab305f7f3750bd67accf9bd1868bac1f42ac"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "aa83c89b8ab17d446d9b09534b258159dd1004aa832d7654c15b8a604cf8b73f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "aarch64"
git-tree-sha1 = "c19926d76852285d6723df7c15f3e8c7288ae428"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "9e7ac661df8cd84167be8c872d831b26551041bf886276500afc85fd20145c15"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56a1300de92cb559088b61133e6ede4e7c6da210"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "45dde9da81a0cc326557a63ef78699594817b65a54a4f5fb087a052791b61c73"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3aca58e29d02139ada4502664d021cb48618767a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "5e9494a9e227bfa4ddec070eb670b3e08214bd8349bf8e6c2b5c4b3397483f0c"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "x86_64"
git-tree-sha1 = "e85245541c57aca4b85c3848f6e7d07b7d87d556"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "3fb64a6095cdf2e2151ed18cb7b292e3cc2a1006a06aa475fd654ef3dbb473b1"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-build_log]]
arch = "i686"
git-tree-sha1 = "ff6896d1656156031fd157e7e2df0464d613e876"
lazy = true
os = "windows"

    [[GCC_crt_objects-build_log.download]]
    sha256 = "45461b5299024df2e4d72558e12af4a58de5f66628099ad3e4b5699c0a5405e5"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-build_log-v9.1.0-i686-w64-mingw32.tar.gz"

[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6c1a948fbfa2bd3ec7b6fa444efab91aceec6593"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "674944df5d98d906d9f5c562ca1f0e1727df0dfaf8f989bcaabe5debd88507cd"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "5cfba3089adace9167308fccc8981ae20bf57757"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "34a3337e9c4cc4543275a209c4d9e6edfac183bc9890867da5bed8679a43e329"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-i686-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2933ac3950a432402cd9f4978462bb4cb481d84a"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "a5dd8db697f1b5bf935d40f20e019e7329cfe1e05cf6c00b80e7406cf475c59f"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b10793e3b09adf217a61b7ad1f58527845d77653"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "8677f5c74725c8d48766a6bcc0a33b31bd0be88e76b567d22d37eaaddc775ec9"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a51a1cb2ca5b6cd62635380339b7d6ec175f4bbe"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "6fd0cc6023d2cb262d9a0f562b2c5495b2e4a00f0ff6d544d7f1475856f79dc2"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "086e54b5cf61e2c75cc857504fdf3b7cc68ebf2d"
lazy = true
libc = "glibc"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "ff2536e34f9240132aed4cbf93c8bbbf4b476182aa1cd31b8bf335b8304dba48"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4a631fc566404d8675e92ca298e704dd0df403e5"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "70ba90d36c8549cebc213abfcdabff4da539d54a8d20153157438f79a1dd39a4"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "11b750ff353dbb27cb409cb7d3dc4028ba5abba7"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "d9285e1a835934cd2020fd69a4f3fc66d8608dab3422891883384e81d3938803"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-i686-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "aarch64"
git-tree-sha1 = "071ad532839c0a127f53da220a8475b26c713509"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "b913927baffaf810d335fd7aa6e5566e54e3a6e37f4cb1501d75c4604fc5d6cf"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab0d97954cb6c217745b1b750d0d1c36553bdac2"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "8c39b7420aa1c26a063126c09bf724d981f4f9203232c4c871186fe7652fd3dc"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a21c4e7912e56403244a4a402bc2e01295a864a"
lazy = true
libc = "musl"
os = "linux"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "cb7bf07f9fd3c98865633e5b0bdff861284f84bcb097e5467d2440d826e9ffc6"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dc0f125da8af919110deba5b6b58bb126294d14a"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "9475bc5cd719090a9a87eefcd1941a92b843a02a182c4695bc886f1f6f08ba5c"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[GCC_crt_objects-extract_log]]
arch = "i686"
git-tree-sha1 = "2fa7edbd594b4215679917e5843b1499b57de33f"
lazy = true
os = "windows"

    [[GCC_crt_objects-extract_log.download]]
    sha256 = "ab9c95bd9788659641a4049f6e9acde155dd015461cacd9b6851b8f4d36a7f74"
    url = "https://github.com/staticfloat/GCC_crt_objects_jll.jl/releases/download/v9.1.0-GCC/GCC_crt_objects-extract_log-v9.1.0-i686-w64-mingw32.tar.gz"
